auth:
  jwksUrl: "https://catenaxdev003akssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth/realms/CX-Central/protocol/openid-connect/certs"
  issuerUrl: "https://catenaxdev003akssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth/realms/CX-Central"
  redirectUrl: "https://managed-identity-wallets.dev.demo.catena-x.net/callback"
  realm: "CX-Central"
  role: "access"
datapoolUrl: "https://catenax-bpdm-dev.germanywestcentral.cloudapp.azure.com"
image:
  registry: "ghcr.io"
  tag: "latest-develop"
acapy:
  logLevel: "DEBUG"
  ledgerUrl: "https://indy-test.bosch-digital.de/"
  endpointPort: "8000"
  endpointUrl: "https://managed-identity-wallets.dev.demo.catena-x.net:8000/"
  adminPort: "11000"
  adminUrl: "http://localhost:11000"
  secret:
    name: "catenax-managed-identity-wallets-acapy-secrets"
    path: "managed-identity-wallets/data/dev/catenax-managed-identity-wallets-acapy-secrets"
certificate:
  host: "managed-identity-wallets.dev.demo.catena-x.net"
managedIdentityWallets:
  secret:
    name: "catenax-managed-identity-wallets-secrets"
    path: "managed-identity-wallets/data/dev/catenax-managed-identity-wallets-secrets"
postgresql:
  secret:
    name: "postgres-managed-identity-wallets-secret-config"
    path: "managed-identity-wallets/data/dev/postgres-managed-identity-wallets-secret-config"
acapypostgresql:
  secret:
    name: "product-managed-identity-wallets-acapy-postgresql"
    path: "managed-identity-wallets/data//dev/postgres-acapy-secret-config"