auth:
  jwksUrl: "http://192.168.205.1:8081/auth/realms/catenax/protocol/openid-connect/certs"
  issuerUrl: "http://192.168.205.1:8081/auth/realms/catenax"
  redirectUrl: "http://localhost:8080/callback"
  realm: "catenax"
  role: "access"
datapoolUrl: "https://catenax-bpdm-dev.germanywestcentral.cloudapp.azure.com"
acapy:
  logLevel: "DEBUG"
  ledgerUrl: "https://indy-test.bosch-digital.de/"
  endpointPort: "8000"
  endpointUrl: "https://managed-identity-wallets.dev.demo.catena-x.net:8000/"
  adminPort: "11000"
  adminUrl: "http://localhost:11000"
  imageName: "acapy"
  tag: "0.7.4-rc1"
certificate:
  host: "managed-identity-wallets.local.demo.catena-x.net"
image:
  name: "catena-x/managed-identity-wallets"
isLocal: true