{{- if not .Values.isLocal }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.acapy.secret.path }}
  name: {{ .Values.acapy.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  acapy-admin-api-key: <acapy-admin-api-key>
  acapy-agent-wallet-seed: <acapy-agent-wallet-seed>
  acapy-db-account: <acapy-db-account>
  acapy-db-admin: <acapy-db-admin>
  acapy-db-admin-password: <acapy-db-admin-password>
  acapy-db-password: <acapy-db-password>
  acapy-jwt-secret: <acapy-jwt-secret>
  acapy-wallet-key: <acapy-wallet-key>
{{- end}}
---
{{- if not .Values.isLocal }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.acapypostgresql.secret.path }}
  name: {{ .Values.acapypostgresql.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: <password>
  postgres-password: <postgres-password>
  user: <user>
{{- end}}
---
{{- if not .Values.isLocal }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.managedIdentityWallets.secret.path }}
  name: {{ .Values.managedIdentityWallets.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  cx-db-jdbc-url: <cx-db-jdbc-url>
  cx-auth-client-id: <cx-auth-client-id>
  cx-auth-client-secret: <cx-auth-client-secret>
{{- end}}
