version: '3'

services:
  cx_postgres:
    image: postgres:14.2
    container_name: cx_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cx_password
      PGDATA: /data/postgres-data
    volumes:
      - postgres-data:/data/postgres-data
    ports:
      - "5432:5432"

  cx_keycloak:
    image: jboss/keycloak:16.1.1
    container_name: cx_keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: catena
      KEYCLOAK_IMPORT: /tmp/catenax-realm.json
    volumes:
      - ./keycloak/catenax-realm.json:/tmp/catenax-realm.json
    ports:
      - "8081:8080"

  cx_acapy:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.4
    container_name: cx_acapy
    ports:
      - "11000:11000"
      - "8000:8000"
    depends_on:
      - cx_postgres
    environment:
      WAIT_HOSTS: "cx_postgres:5432"
      WAIT_HOSTS_TIMEOUT: "300"
      WAIT_SLEEP_INTERVAL: "5"
      WAIT_HOST_CONNECT_TIMEOUT: "3"
    entrypoint: /bin/bash
    command: [
       "-c",
       "aca-py start \
        -e http://localhost:8000/ \
        --auto-provision \
        --inbound-transport http '0.0.0.0' 8000 \
        --outbound-transport http \
        --admin '0.0.0.0' 11000 \
        --wallet-name catenaX \
        --wallet-type indy \
        --wallet-key issuerKeySecret19 \
        --wallet-storage-type postgres_storage
        --wallet-storage-config '{\"url\":\"cx_postgres:5432\",\"max_connections\":5}'
        --wallet-storage-creds '{\"account\":\"postgres\",\"password\":\"cx_password\",\"admin_account\":\"postgres\",\"admin_password\":\"cx_password\"}'
        --seed 00000000000000000000000111111119 \
        --genesis-url https://indy-test.idu.network/genesis \
        --label CatenaXIssuer \
        --admin-api-key Hj23iQUsstG!dde \
        --auto-ping-connection \
        --jwt-secret jwtSecret19 \
        --multitenant \
        --multitenant-admin \
        --log-level DEBUG",
    ]

  cx_revocation_service:
    image: registry.gitlab.com/gaia-x/data-infrastructure-federation-services/not/notarization-service/revocation:1.0.0-SNAPSHOT-quarkus-2.10.2.Final-java17
    container_name: cx_revocation_service
    ports:
      - "8086:8086"
    depends_on:
      - cx_postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://cx_postgres:5432/miwdev?user=miwdevuser&password=^cXnF61qM1kf
      QUARKUS_HTTP_PORT: 8086
      QUARKUS_HTTP_ACCESS_LOG_ENABLED: "true"
      REVOCATION_BASE_URL: http://localhost:8080/api/credentials/
      REVOCATION_MIN_ISSUE_INTERVAL: 2
      QUARKUS_REST_CLIENT_SSI_ISSUANCE_API_URL: "${SSI_SERVICE_URL:-http://host.docker.internal:8080}"
      WAIT_HOSTS: "cx_postgres:5432"
      WAIT_HOSTS_TIMEOUT: "300"
      WAIT_SLEEP_INTERVAL: "5"
      WAIT_HOST_CONNECT_TIMEOUT: "3"

volumes:
  postgres-data:
